#!/usr/bin/env python3
"""Compatibility entry point for the reference-first Candidate A weight study.

The former Jost-700-for-everything implementation is superseded. Candidate B
was rejected by the human and MUST NOT be regenerated by this command.
Historical A/B artifacts remain unapproved records, not production assets.
"""
from build_typography_weights import build

if __name__ == '__main__':
    build()
